### ISSUE TITLE
currentTrack function Error from AppleScript

### ISSUE THREAD

**Issue by YouNesta** [airtoxin/local-itunes#2]
Hi, 

Thanks you for this module. 

I've a problem when a execute the currentTrack function

`{ Error: Command failed: 0:45: execution error: Error on line 1: Error: Une erreur de concordance de type de descripteur est survenue. (-10001)

```
at ChildProcess.onExit (/Users/Younes/Sites/NodeJS/LyricServer/node_modules/duplex-child-process/index.js:116:12)
at ChildProcess.g (events.js:286:16)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:492:12) killed: undefined, code: 1, signal: null }`
```

Can you help me ? 

thanks, sorry for my bad english :/

**Comment by airtoxin** [comment]
thanks issue.

It may be iTunes version problem.
I'll try to fix.

thank you.

**Comment by YouNesta** [comment]
Thanks you you for the futur fix :) if you need help with the NodeJS i'm here ;)
